name: 'Auto Release'
description: 'Auto-create releases on push'
inputs:
    title:
        description: 'Title for the release'
        required: false
        default: 'v$version'
    tag:
        description: 'Name for the git tag'
        required: false
        default: 'v$version'
    draft:
        description: 'Whether or not this release should be published as a draft'
        required: false
        default: 'false'
    changelog:
        description: 'The path to the CHANGELOG'
        required: false
        default: 'CHANGELOG.md'
    changelog-entry:
        description: 'String a CHANGELOG entry must contain to be used as the entry for this release'
        required: false
        default: 'v$version'
outputs:
    success:
        description: 'Whether or not a release was created'
    id:
        description: 'The id of the release'
    version:
        description: 'The version that was released'
    releaseUrl:
        description: 'The URL users can navigate to in order to view the release'
runs:
    using: 'node16'
    main: 'build/index.js'
